version: "3.2"

services:
    db:
       image: mongo:4.2
       container_name: db
       restart: always
       ports: 
         - ${DB_PORT}:27017
       environment:
             MONGO_INITDB_DATABASE: ${DB_NAME}
      
    app:
       container_name: api
       restart: always
       env_file:
         - .env
       depends_on: 
         - db
       build: .
       command: npm start
       ports:
         - ${SERVER_PORT}:${SERVER_PORT}
       volumes:
         - .:/user/app